from django.urls import path


from .views import (index, CookListView, CookCreateView, CookDetailView,
                    CookDeleteView, CookUpdateView,
                    YearsOfExperienceUpdateView, DishListView,
                    DishDetailView, DishCreateView,
                    DishUpdateView, DishDeleteView,
                    AssignCookView, RemoveCookView,
                    DishTypeListView, DishTypeCreateView,
                    DishTypeUpdateView, DishTypeDeleteView,
                    IngredientListView, IngredientCreateView,
                    IngredientUpdateView, IngredientDeleteView)



urlpatterns = [
    path("", index, name="index"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("cooks/create/", CookCreateView.as_view(), name="cook-create"),
    path("cooks/<int:pk>/", CookDetailView.as_view(), name="cook-detail"),
    path("cooks/<int:pk>/delete/",
         CookDeleteView.as_view(),
         name="cook-delete"),
    path("cooks/<int:pk>/update/",
         CookUpdateView.as_view(),
         name="cook-update"),
    path("cooks/<int:pk>/update_years_of_experience/",
         YearsOfExperienceUpdateView.as_view(),
         name="years-of-experience-update"),
    path("dishes/",
         DishListView.as_view(),
         name="dish-list"),
    path("dishes/<int:pk>/",
         DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/",
         DishCreateView.as_view(), name="dish-create"),
    path("dishes/<int:pk>/update/",
         DishUpdateView.as_view(), name="dish-update"),
    path("dishes/<int:pk>/delete/",
         DishDeleteView.as_view(), name="dish-delete"),
    path("dishes/<int:pk>/assign_cook/",
         AssignCookView.as_view(), name="assign_cook"),
    path("dishes/<int:pk>/remowe_cook/",
         RemoveCookView.as_view(), name="remove_cook"),
    path("dishtypes/", DishTypeListView.as_view(),
         name="dishtype-list"),
    path("dishtypes/create/", DishTypeCreateView.as_view(),
         name="dishtype-create"),
    path("dishtypes/<int:pk>/update/", DishTypeUpdateView.as_view(),
         name="dishtype-update"),
    path("dishtypes/<int:pk>/delete/", DishTypeDeleteView.as_view(),
         name="dishtype-delete"),
    path("ingredients/", IngredientListView.as_view(),
         name="ingredient-list"),
    path("ingredients/create/", IngredientCreateView.as_view(),
         name="ingredient-create"),
    path("ingredients/<int:pk>/update/", IngredientUpdateView.as_view(),
         name="ingredient-update"),
    path("ingredients/<int:pk>/delete/", IngredientDeleteView.as_view(),
         name="ingredient-delete"),

]
