# Generated by Django 5.2 on 2025-05-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="dishes",
            field=models.ManyToManyField(
                blank=True, related_name="ingredients", to="kitchen.dish"
            ),
        ),
    ]
